spring:
  cloud:
    gateway:
      routes:
        - id: test_route01
          uri: https://www.bilibili.com
          predicates:
            - Query=url,bilibili

        - id: test_route02
          uri: https://www.4399.com
          predicates:
            - Query=url,4399

        - id: product_route
          uri: lb://xiguamall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
      ## 前端项目请求都带/api前缀，默认路由到aming_route,lb指的是负载均衡
